In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Change the trending date to datetime and possibly publish_time

In [17]:
us_df = pd.read_csv("USvideos.csv")
us_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40949 entries, 0 to 40948
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   video_id                40949 non-null  object
 1   trending_date           40949 non-null  object
 2   title                   40949 non-null  object
 3   channel_title           40949 non-null  object
 4   category_id             40949 non-null  int64
 5   publish_time            40949 non-null  object
 6   tags                    40949 non-null  object
 7   views                   40949 non-null  int64
 8   likes                   40949 non-null  int64
 9   dislikes                40949 non-null  int64
 10  comment_count           40949 non-null  int64
 11  thumbnail_link          40949 non-null  object
 12  comments_disabled       40949 non-null  bool
 13  ratings_disabled        40949 non-null  bool
 14  video_error_or_removed  40949 non-null  bool
 15  description             40379 non-null  object
dtypes: bool(3), int64(5), object(8)
memory usage: 4.2+ MB

In [18]:
ca_df = pd.read_csv("CAvideos.csv")
ca_df.head()

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description
0,n1WpP7iowLc,17.14.11,Eminem - Walk On Water (Audio) ft. Beyoncé,EminemVEVO,10,2017-11-10T17:00:03.000Z,"Eminem|""Walk""|""On""|""Water""|""Aftermath/Shady/In...",17158579,787425,43420,125882,https://i.ytimg.com/vi/n1WpP7iowLc/default.jpg,False,False,False,Eminem's new track Walk on Water ft. Beyoncé i...
1,0dBIkQ4Mz1M,17.14.11,PLUSH - Bad Unboxing Fan Mail,iDubbbzTV,23,2017-11-13T17:00:00.000Z,"plush|""bad unboxing""|""unboxing""|""fan mail""|""id...",1014651,127794,1688,13030,https://i.ytimg.com/vi/0dBIkQ4Mz1M/default.jpg,False,False,False,STill got a lot of packages. Probably will las...
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146035,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...
3,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095828,132239,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...
4,2Vv-BfVoq4g,17.14.11,Ed Sheeran - Perfect (Official Music Video),Ed Sheeran,10,2017-11-09T11:04:14.000Z,"edsheeran|""ed sheeran""|""acoustic""|""live""|""cove...",33523622,1634130,21082,85067,https://i.ytimg.com/vi/2Vv-BfVoq4g/default.jpg,False,False,False,🎧: https://ad.gt/yt-perfect\n💰: https://atlant...

### Dictionary below defining original data set categories to their associated genre.

In [19]:
youtube_categories = {
    1: "Film & Animation",
    2: "Autos & Vehicles",
    10: "Music",
    15: "Pets & Animals",
    17: "Sports",
    18: "Short Movies",
    19: "Travel & Events",
    20: "Gaming",
    21: "Videoblogging",
    22: "People & Blogs",
    23: "Comedy",
    24: "Entertainment",
    25: "News & Politics",
    26: "Howto & Style",
    27: "Education",
    28: "Science & Technology",
    29: "Nonprofits & Activism",
    30: "Movies",
    31: "Anime/Animation",
    32: "Action/Adventure",
    33: "Classics",
    34: "Comedy",
    35: "Documentary",
    36: "Drama",
    37: "Family",
    38: "Foreign",
    39: "Horror",
    40: "Sci-Fi/Fantasy",
    41: "Thriller",
    42: "Shorts",
    43: "Shows",
    44: "Trailers"
}

### Canada adding category genres to IDs

In [20]:
ca_df["youtube_category_name"] = ca_df["category_id"].map(youtube_categories)

### US adding category genres to IDs

In [21]:
us_df["youtube_category_name"] = us_df["category_id"].map(youtube_categories)

### US top views by category name

In [22]:
us_df.groupby("youtube_category_name")[["views", "likes", "dislikes"]].sum().sort_values("views", ascending=False)

                             views       likes  dislikes
youtube_category_name
Music                  40132892190  1416838584  51179008
Entertainment          20604388195   530516491  42987663
Film & Animation        7284156721   165997476   6075148
Comedy                  5117426208   216346746   7230391
People & Blogs          4917191726   186615999  10187901
Sports                  4404456673    98621211   5133551
Howto & Style           4078545064   162880075   5473899
Science & Technology    3487756816    82532638   4548402
Gaming                  2141218625    69038284   9184466
News & Politics         1473765704    18151033   4180049
Education               1180629990    49257772   1351972
Pets & Animals           764651989    19370702    527379
Autos & Vehicles         520690717     4245656    243010
Travel & Events          343557084     4836246    340427
Nonprofits & Activism    168941392    14815646   3310381
Shows                     51501058     1082639     24508

### Canada top views by category name
Looked at the relationship between Canada and US to get a general idea of how the two countries compare. May elaborate more after initial US analysis.

In [27]:
ca_df.groupby("youtube_category_name")[["views", "likes", "dislikes"]].sum().sort_values("views", ascending=False)

                             views      likes  dislikes
youtube_category_name
Entertainment          13671215509  387245433  25791583
Music                  13179850194  564447530  22098190
Comedy                  3708438785  196046674   5372515
People & Blogs          3228227926  105388564   9480796
Sports                  2997652188   59449419   3286369
Film & Animation        2939060844   77802003   3111259
News & Politics         1614610043   32705054   3264041
Howto & Style           1570846611   51183104   1730520
Science & Technology    1425090421   42814598   1791153
Gaming                  1241532385   51726552   2446882
Education                531773343   20972402    793448
Pets & Animals           235592173    8830736    185003
Autos & Vehicles         200066074    4732114    197776
Travel & Events          143746952    3750914    129861
Nonprofits & Activism    115601623   10242613   2325807
Shows                     71549508     589263    120436
Movies                    17120490     252905     12280

In [23]:
us_df.sample(5)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,youtube_category_name
10812,D-pKeb6Wf4U,18.07.01,Marshmello - Love U (Official Music Video),marshmello,10,2018-01-05T14:00:00.000Z,"marshmello|""marshmallow""|""you and me""|""keep it...",1589597,113644,3268,10212,https://i.ytimg.com/vi/D-pKeb6Wf4U/default.jpg,False,False,False,Get your NEW Mello™️ by Marshmello gear HERE ▶...,Music
23990,aC5lxLCyyhQ,18.16.03,Life Itself - Teaser Trailer [HD] | Amazon Stu...,Amazon Studios,1,2018-03-14T02:00:01.000Z,"Amazon Studios|""Amazon""|""amazon prime""|""amazon...",525797,502,67,76,https://i.ytimg.com/vi/aC5lxLCyyhQ/default.jpg,False,False,False,Life Itself centers on a couple (Oscar Isaac a...,Film & Animation
22827,-s3j-ptJD10,18.10.03,The Logistics of Living in Antarctica,Wendover Productions,27,2018-03-06T15:30:00.000Z,"antarctica|""arctic""|""south pole""|""south""|""pole...",731819,23746,420,1990,https://i.ytimg.com/vi/-s3j-ptJD10/default.jpg,False,False,False,Get 20% off Brilliant premium by being one of ...,Education
1747,eKwAib6LosM,17.22.11,Miguel - Pineapple Skies (Audio),MiguelVEVO,10,2017-11-17T05:00:01.000Z,"ByStorm Entertainment/RCA Records|""Miguel""|""Pi...",396378,16263,169,911,https://i.ytimg.com/vi/eKwAib6LosM/default.jpg,False,False,False,War & Leisure - Available Everywhere Dec 1 201...,Music
7180,hphLiGW6FgE,17.19.12,'Wonder Woman' Director Patty Jenkins on Picki...,The Hollywood Reporter,24,2017-12-13T17:56:18.000Z,"thr|""the hollywood reporter""|""hollywood report...",31319,632,17,155,https://i.ytimg.com/vi/hphLiGW6FgE/default.jpg,False,False,False,"Subscribe for Roundtables, Box Office Reports,...",Entertainment

In [24]:
us_df.head(5)

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,youtube_category_name
0,2kyS6SvSYSE,17.14.11,WE WANT TO TALK ABOUT OUR MARRIAGE,CaseyNeistat,22,2017-11-13T17:13:01.000Z,SHANtell martin,748374,57527,2966,15954,https://i.ytimg.com/vi/2kyS6SvSYSE/default.jpg,False,False,False,SHANTELL'S CHANNEL - https://www.youtube.com/s...,People & Blogs
1,1ZAPwfrtAFY,17.14.11,The Trump Presidency: Last Week Tonight with J...,LastWeekTonight,24,2017-11-13T07:30:00.000Z,"last week tonight trump presidency|""last week ...",2418783,97185,6146,12703,https://i.ytimg.com/vi/1ZAPwfrtAFY/default.jpg,False,False,False,"One year after the presidential election, John...",Entertainment
2,5qpjK5DgCt4,17.14.11,"Racist Superman | Rudy Mancuso, King Bach & Le...",Rudy Mancuso,23,2017-11-12T19:05:24.000Z,"racist superman|""rudy""|""mancuso""|""king""|""bach""...",3191434,146033,5339,8181,https://i.ytimg.com/vi/5qpjK5DgCt4/default.jpg,False,False,False,WATCH MY PREVIOUS VIDEO ▶ \n\nSUBSCRIBE ► http...,Comedy
3,puqaWrEC7tY,17.14.11,Nickelback Lyrics: Real or Fake?,Good Mythical Morning,24,2017-11-13T11:00:04.000Z,"rhett and link|""gmm""|""good mythical morning""|""...",343168,10172,666,2146,https://i.ytimg.com/vi/puqaWrEC7tY/default.jpg,False,False,False,Today we find out if Link is a Nickelback amat...,Entertainment
4,d380meD0W0M,17.14.11,I Dare You: GOING BALD!?,nigahiga,24,2017-11-12T18:01:41.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""i dare you""|""...",2095731,132235,1989,17518,https://i.ytimg.com/vi/d380meD0W0M/default.jpg,False,False,False,I know it's been a while since we did this sho...,Entertainment

In [25]:
us_df[us_df.duplicated()].shape

(48, 17)

### Duplicates found, need to remove

In [26]:
duplicates = us_df[us_df.duplicated(keep=False)]
duplicates.sort_values("views")

,video_id,trending_date,title,channel_title,category_id,publish_time,tags,views,likes,dislikes,comment_count,thumbnail_link,comments_disabled,ratings_disabled,video_error_or_removed,description,youtube_category_name
34923,D2mxKEa2xmA,18.15.05,10 Most DEVASTATING Cyber Attacks in History,MatthewSantoro,24,2018-05-13T13:00:01.000Z,"computer hacks|""cyber attack""|""computer virus""...",158406,6773,364,947,https://i.ytimg.com/vi/D2mxKEa2xmA/default.jpg,False,False,False,"Download the best VPN on the market, NORDVPN n...",Entertainment
34774,D2mxKEa2xmA,18.15.05,10 Most DEVASTATING Cyber Attacks in History,MatthewSantoro,24,2018-05-13T13:00:01.000Z,"computer hacks|""cyber attack""|""computer virus""...",158406,6773,364,947,https://i.ytimg.com/vi/D2mxKEa2xmA/default.jpg,False,False,False,"Download the best VPN on the market, NORDVPN n...",Entertainment
34945,zcEE8J2Bqa8,18.15.05,The Goblin - JACK AND DEAN,Jack and Dean,23,2018-05-11T18:27:01.000Z,"Jack and Dean|""OMFGItsJackAndDean""|""Jack Howar...",165617,20572,140,1407,https://i.ytimg.com/vi/zcEE8J2Bqa8/default.jpg,False,False,False,That? That's a goblin living under the stairs....,Comedy
34796,zcEE8J2Bqa8,18.15.05,The Goblin - JACK AND DEAN,Jack and Dean,23,2018-05-11T18:27:01.000Z,"Jack and Dean|""OMFGItsJackAndDean""|""Jack Howar...",165617,20572,140,1407,https://i.ytimg.com/vi/zcEE8J2Bqa8/default.jpg,False,False,False,That? That's a goblin living under the stairs....,Comedy
34768,1U1u5aKU3AY,18.15.05,New lava fissures fuel fears of eruption in Ha...,CNN,25,2018-05-13T19:30:53.000Z,"latest News|""Happening Now""|""CNN""|""lava""|""hawa...",241387,1488,251,1087,https://i.ytimg.com/vi/1U1u5aKU3AY/default.jpg,False,False,False,Three new fissures have opened on Hawaii's Big...,News & Politics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34927,UfKmSfgFxi8,18.15.05,FORTNITE The Movie (Official Fake Trailer),nigahiga,24,2018-05-11T21:11:16.000Z,"ryan|""higa""|""higatv""|""nigahiga""|""fortnite""|""th...",8289563,408385,10966,21837,https://i.ytimg.com/vi/UfKmSfgFxi8/default.jpg,False,False,False,Play Fortnite for FREE here: https://pixly.go2...,Entertainment
34794,oSEeK9yDNQI,18.15.05,Clash Royale: Meet the Rascals! (New Card!),Clash Royale,20,2018-05-10T13:19:23.000Z,"Clash Royale|""Clash Royale Game""|""Supercell""|""...",13418844,258720,22805,19877,https://i.ytimg.com/vi/oSEeK9yDNQI/default.jpg,False,False,False,Rascals! What have they done now...New Card Ou...,Gaming
34943,oSEeK9yDNQI,18.15.05,Clash Royale: Meet the Rascals! (New Card!),Clash Royale,20,2018-05-10T13:19:23.000Z,"Clash Royale|""Clash Royale Game""|""Supercell""|""...",13418844,258720,22805,19877,https://i.ytimg.com/vi/oSEeK9yDNQI/default.jpg,False,False,False,Rascals! What have they done now...New Card Ou...,Gaming
34941,uxbQATBAXf8,18.15.05,Deadpool 2 | With Apologies to David Beckham,20th Century Fox,1,2018-05-10T14:24:29.000Z,"Trailer|""Deadpool""|""20th Century Fox (Producti...",15960127,374825,3823,9059,https://i.ytimg.com/vi/uxbQATBAXf8/default.jpg,False,False,False,Get your Deadpool 2 tickets at http://www.Dead...,Film & Animation
34792,uxbQATBAXf8,18.15.05,Deadpool 2 | With Apologies to David Beckham,20th Century Fox,1,2018-05-10T14:24:29.000Z,"Trailer|""Deadpool""|""20th Century Fox (Producti...",15960127,374825,3823,9059,https://i.ytimg.com/vi/uxbQATBAXf8/default.jpg,False,False,False,Get your Deadpool 2 tickets at http://www.Dead...,Film & Animation

### look to see how correlation between dislikes may drive views